spring:
  application:
    name: jifen-api
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.237.229:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 1000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    init-method: init

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
paypal.mode: sandbox
paypal.client.app: AYbTOnmDhdx_553M9oY7zlHpIZ-hRfZkQ9o8xMlgJ17oLRRgg6w30yj4JTg6Y8j_8mpyzv-fMvKvFxwY
paypal.client.secret: ECN4-QHs3tc48ybBNhe8Gx0sTl3agT04_GaYFClKaYzbsQsLMlwNHN6mTsnfg5-TEbQr8ZxHSObF6A5Y
